version: "3"
services:
  showcase:
    build: showcase
    volumes:
      - ./showcase:/app
    ports:
      - 3000:7860

  fastapi:
    build: fastapi
    volumes:
      - ./fastapi:/app
    ports:
      - 8000:8000
